name: drug-pareto-rl
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - cpuonly
  - rdkit
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - tqdm
  - joblib
  - seaborn
  - pytest
  - pip
